(function() {var implementors = {};
implementors["argmin_core"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"argmin_core/struct.ArgminKV.html\" title=\"struct argmin_core::ArgminKV\">ArgminKV</a>",synthetic:false,types:["argmin_core::kv::ArgminKV"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"argmin_core/struct.ArgminLogger.html\" title=\"struct argmin_core::ArgminLogger\">ArgminLogger</a>",synthetic:false,types:["argmin_core::logging::ArgminLogger"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"argmin_core/struct.ArgminWriter.html\" title=\"struct argmin_core::ArgminWriter\">ArgminWriter</a>&lt;T&gt;",synthetic:false,types:["argmin_core::output::ArgminWriter"]},{text:"impl&lt;T:&nbsp;<a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a>&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"struct\" href=\"argmin_core/struct.ArgminResult.html\" title=\"struct argmin_core::ArgminResult\">ArgminResult</a>&lt;T&gt;",synthetic:false,types:["argmin_core::result::ArgminResult"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/default/trait.Default.html\" title=\"trait core::default::Default\">Default</a> for <a class=\"enum\" href=\"argmin_core/enum.TerminationReason.html\" title=\"enum argmin_core::TerminationReason\">TerminationReason</a>",synthetic:false,types:["argmin_core::termination::TerminationReason"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
